spring:
  datasource:
    url: jdbc:postgresql://${BDD_URL}
    username: ${BDD_USER}
    password: ${BDD_PWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: warn

url-front: ${URL_FRONT}