name: test_build

on: [ push ]

jobs:
  deploy_back_heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.APP_NAME_BACK}}
          heroku_email: ${{secrets.EMAIL}}
          appdir: "api-course"
        env:
          HD_URL_FRONT: ${{secrets.URL_APP_FRONT}}
          
  deploy_front_heroku:
    needs: deploy_back_heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        working-directory: ./front-course
        run: |
          touch .env
          echo API_URL=${{secrets.URL_APP_BACK}} >> .env
          echo PORT=8080 >> .env
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.APP_NAME_FRONT}}
          heroku_email: ${{secrets.EMAIL}}
          appdir: "front-course"
          procfile: "web: npm run start:prod"