name: test_build

on: [ push ]

jobs:
  build_test_back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Maven tests
        working-directory: ./api-course
        run: mvn test

      - name: Maven package
        working-directory: ./api-course
        run: mvn package
