name: test_build

on: [ push ]

jobs:
  build_test_back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Maven tests and packages
        working-directory: ./api-course
        run: |
            mvn test
            mvn package
            
  build_test_front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: npm install and npm run build
        working-directory: ./front-course
        run: |
          npm clean-install
          npm run build

  deploy_back_heroku:
    needs: [build_test_back, build_test_front]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.APP_NAME_BACK}}
          heroku_email: ${{secrets.EMAIL}}
          appdir: "api-course"
        env:
          URL_FRONT: ${{secrets.URL_APP_FRONT}}
          
  deploy_front_heroku:
    needs: deploy_back_heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.APP_NAME_FRONT}}
          heroku_email: ${{secrets.EMAIL}}
          appdir: "front-course"
          procfile: "web: npm start:prod"
          env_file: ".env"
        env:
          API_URL: ${{secrets.URL_APP_BACK}}
          PORT: 8080