name: test_build

on: [ push ]

jobs:
  deploy_back_heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.APP_NAME_BACK}}
          heroku_email: ${{secrets.EMAIL}}
          appdir: "api-course"
        env:
          URL_FRONT: ${{secrets.URL_APP_FRONT}}
          
  deploy_front_heroku:
    needs: deploy_back_heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_API_URL: ${{secrets.URL_APP_BACK}}
          envkey_PORT: 8080
          directory: ./front-course
          file_name: .env
      - name: visualise file in folder
        working-directory: ./front-course
        run: ls
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.APP_NAME_FRONT}}
          heroku_email: ${{secrets.EMAIL}}
          appdir: "front-course"
          env_file: ".env"
          procfile: "web: npm run start:prod"